POST http://localhost:8080/api/students
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiaWF0IjoxNzM2ODIyNzM5LCJleHAiOjE3Mzk0MTQ3Mzl9.Hg5I9tHycS6XKE-2JYFEXMQGiPTZlNbF_9EqecC37jM

{
    "data":{
        "name": "Thanachai Loklueng",
        "mobile": "0943301218",
        "cardId": "1600101914175"
    }
}
